-- Shaman
QUICKHEAL_SPELL_CHAIN_HEAL = "Chain Heal";
QUICKHEAL_SPELL_LESSER_HEALING_WAVE = "Lesser Healing Wave";
QUICKHEAL_SPELL_HEALING_WAVE = "Healing Wave";

-- Priest
QUICKHEAL_SPELL_LESSER_HEAL = 'Lesser Heal';
QUICKHEAL_SPELL_HEAL = 'Heal';
QUICKHEAL_SPELL_GREATER_HEAL = 'Greater Heal';
QUICKHEAL_SPELL_FLASH_HEAL = 'Flash Heal';
QUICKHEAL_SPELL_RENEW = 'Renew';

-- Paladin
QUICKHEAL_SPELL_HOLY_LIGHT = 'Holy Light';
QUICKHEAL_SPELL_FLASH_OF_LIGHT = 'Flash of Light';

-- Druid
QUICKHEAL_SPELL_HEALING_TOUCH = 'Healing Touch';
QUICKHEAL_SPELL_REGROWTH = 'Regrowth';
QUICKHEAL_SPELL_REJUVENATION = 'Rejuvenation';

FILTER_MTLIST_SHOW = 'Main Tanks';
FILTER_MELEEDPSLIST_SHOW = 'Melee DPS';
FILTER_RANGEDDPSLIST_SHOW = 'Ranged DPS';

QH_STR_MT_PRIO_LIST = 'Main Tanks';
QH_STR_MTLIST = 'Main Tanks';
QH_STR_RANGEDDPSLIST = 'Main Tanks';
QH_CLR_MTLIST = 'C';
QH_CLR_MELEEDPSLIST = 'C';